### ISSUE TITLE
Access to servers with TLSv1 is no longer supported

### ISSUE THREAD

**Issue by fbricon** [takari/aether-connector-okhttp#20]
We failed to catch the issue earlier, as our tests reused locally cached data, but when a remote repository uses TLSv1, the connector fails to connect, as TLSv1 support was removed from [OkHttp 3.13.0](
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130)

https://ci-staging.eclipse.org/m2e/job/m2e-master/351/testReport/junit/org.eclipse.m2e.core.internal.project.registry/RegistryTest/testInvalidParent/ 

junit.framework.AssertionFailedError: expected:<Optional.empty> but was:<Optional[Marker [on: /invalidParent/pom.xml, id: 30, type: org.eclipse.m2e.core.maven2Problem.pomloading, attributes: [columnEnd: 9, columnStart: 1, lineNumber: 3, message: Project build error: Non-resolvable parent POM for org.eclipse.m2e.tests.invalidParent:invalidParent:1: Could not transfer artifact io.takari:takari:pom:28 from/to eclipse.maven.central.mirror (https://repo.eclipse.org/content/repositories/maven_central/): Server chose TLSv1, but that protocol version is not enabled or not supported by the client. and 'parent.relativePath' points at wrong local POM, severity: 2, transient: false], created: 5/28/19 6:43 PM]]>	at org.eclipse.m2e.core.internal.project.registry.RegistryTest.testInvalidParent(RegistryTest.java:90)

Should be fixable by enabling the protocols on the client 
```java
OkHttpClient client = new OkHttpClient.Builder()
    .connectionSpecs(Arrays.asList(ConnectionSpec.COMPATIBLE_TLS))
    .build();
```

**Comment by mosabua** [comment]
so do we need to fix something in this project and cut a new release? Also .,. do we need to migrate this to maven-resolver some time soon?

**Comment by fbricon** [comment]
I'm working on a fix right now.
Migration to maven-resolver is not urgent at the moment, but yeah we should consider it.

**Comment by tony--** [comment]
Thanks for the fix @fbricon.  Glad that the version bump (#19) can stay on track.
