### ISSUE TITLE
AetherClientProxy has no support for nonProxyHosts/noProxy

### ISSUE THREAD

**Issue by tony--** [takari/aether-connector-okhttp#24]
I'm working on m2e-core in a proxied environment.  Some of the tests fail when a proxy is set in maven settings, but pass when no proxy is set.  Of course, removing the proxy causes other tests to fail.

After debugging this, I found that the failing tests are failing because they are attempting to use proxy to reach localhost/127.0.0.1.  I have nonProxyHosts set in my maven settings, but upon further debugging I noticed that nonProxyHosts is ignored in OkHttpWagon.openConnectionInternal because AetherClientProxy does not have any property for nonProxyHosts.

This seriously limits the usability of aether-connector-okhttp in proxied environments.

**Comment by cstamas** [comment]
This repo is being archived
