### ISSUE TITLE
Preemtive authentication configuration

### ISSUE THREAD

**Issue by emenaceb** [takari/aether-connector-okhttp#30]
It will be nice to have a configuration to use preemtive authentication like in

https://maven.apache.org/guides/mini/guide-http-settings.html#Example:_Using_Preemptive_Authentication

Not only against proxies, but also against servers
Use case: Some Artifactory configurations force to use preemptive authentication.

**Comment by michael-o** [comment]
When they force you to use then they are broken. There is nothing wrong in doing `Expect: 100-continue`.

**Comment by cstamas** [comment]
This repo is being archived
